---

nginx_revproxy_sites:                                         # List of sites to reverse proxy
  example.com:                                                # Domain name
    domains:                                                  # List of server_name aliases
      - example.com
      - www.example.com
    upstreams:                                                # List of Upstreams
      - { backend_address: localhost, backend_port: 5000 }
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: false                                        # Set to True if you want use letsencrypt
    letsencrypt_email: ""                                     # Set email for letencrypt cert
